version: "3.9"

services:
  web:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    cap_add: [NET_ADMIN]
    depends_on: [db, redis]

  celery:
    build: .
    command: celery -A config worker -l info
    env_file: .env
    depends_on: [redis, db]

  redis:
    image: redis:7

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: wireguard
      POSTGRES_USER: wireguard
      POSTGRES_PASSWORD: wireguard
